name: ai-travel-planner
channels:
  - conda-forge
  - defaults
  - pytorch
  - nvidia
dependencies:
  - python=3.10
  - pip>=23.0
  - setuptools>=65.0
  - wheel>=0.37.0
  - git>=2.25.0
  
  # 系统工具
  - curl>=7.68.0
  - wget>=1.20.0
  - unzip>=6.0
  
  # 数据库工具
  - mysql-connector-python>=8.0.33
  - redis-py>=4.5.0
  
  # 机器学习基础
  - numpy>=1.24.0
  - pandas>=2.0.0
  - scikit-learn>=1.3.0
  
  # PyTorch (CUDA 支持)
  - pytorch=2.5.1
  - torchvision>=0.16.0
  - torchaudio>=2.1.0
  - pytorch-cuda=11.8
  
  # 开发工具
  - pre-commit>=3.0.0
  - black>=23.0.0
  - isort>=5.12.0
  - flake8>=6.0.0
  - pytest>=7.4.0
  - pytest-cov>=4.1.0
  - pytest-asyncio>=0.21.0
  
  # Jupyter
  - jupyter>=1.0.0
  - jupyterlab>=4.0.0
  - ipython>=8.0.0
  
  # pip安装的包
  - pip:
    # Web框架
    - fastapi==0.115.6
    - uvicorn[standard]==0.32.1
    - websockets==14.1
    - starlette==0.41.3
    
    # AI/ML框架
    - langchain==0.3.12
    - langchain-community==0.3.12
    - langchain-openai==0.2.14
    - openai==1.61.0
    - transformers==4.47.1
    - sentence-transformers==3.3.1
    - vllm==0.8.5
    
    # 数据验证和ORM
    - pydantic==2.10.4
    - pydantic-settings==2.7.0
    - sqlalchemy==2.0.36
    - alembic==1.14.0
    - asyncpg==0.30.0
    - aiomysql==0.2.0
    
    # 缓存和消息队列
    - redis==5.2.1
    - celery==5.4.0
    - kombu==5.4.2
    
    # 向量数据库
    - qdrant-client==1.14.1
    - chromadb==0.5.23
    
    # 搜索引擎
    - elasticsearch==8.16.0
    
    # HTTP客户端
    - httpx==0.28.1
    - aiohttp==3.11.11
    - requests==2.32.3
    
    # 数据处理
    - beautifulsoup4==4.12.3
    - lxml==5.3.0
    - pypdf==5.1.0
    - python-multipart==0.0.20
    
    # 配置管理
    - python-dotenv==1.0.1
    - pyyaml==6.0.2
    - toml==0.10.2
    
    # 认证和安全
    - python-jose[cryptography]==3.3.0
    - passlib[bcrypt]==1.7.4
    - cryptography==44.0.0
    
    # 监控和日志
    - prometheus-client==0.21.1
    - structlog==24.4.0
    - loguru==0.7.3
    
    # 时间处理
    - python-dateutil==2.9.0
    - pytz==2024.2
    
    # 图像处理
    - pillow==11.0.0
    
    # 模板引擎
    - jinja2==3.1.4
    
    # 开发工具
    - rich==14.0.0
    - typer==0.15.1
    - click==8.1.8
    
    # 测试工具
    - factory-boy==3.3.1
    - freezegun==1.6.0
    - responses==0.25.4
    
    # 类型提示
    - mypy==1.14.0
    - types-redis==4.6.0.20241218
    - types-requests==2.32.0.20241218

variables:
  CONDA_ENV_NAME: ai-travel-planner
  PYTHONPATH: $CONDA_PREFIX/lib/python3.10/site-packages
  CUDA_VISIBLE_DEVICES: "0" 